name: pop3d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch==1.10.1 
  - torchvision==0.11.2 
  - cudatoolkit=11.3
  - pillow
  - timm
  - yaml
  - wandb
  - numba
  - pip:
      - pyquaternion
      - nuscenes-devkit
      - ipython
      - openmim
      - ftfy
      - "mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html"
      - mmsegmentation==0.30.0
      - mmdet==2.21.0
      - yapf==0.40.1
      - "git+https://github.com/openai/CLIP.git"
      - prettytable
