labels:
  0: 'noise'
  1: 'animal'
  2: 'human.pedestrian.adult'
  3: 'human.pedestrian.child'
  4: 'human.pedestrian.construction_worker'
  5: 'human.pedestrian.personal_mobility'
  6: 'human.pedestrian.police_officer'
  7: 'human.pedestrian.stroller'
  8: 'human.pedestrian.wheelchair'
  9: 'movable_object.barrier'
  10: 'movable_object.debris'
  11: 'movable_object.pushable_pullable'
  12: 'movable_object.trafficcone'
  13: 'static_object.bicycle_rack'
  14: 'vehicle.bicycle'
  15: 'vehicle.bus.bendy'
  16: 'vehicle.bus.rigid'
  17: 'vehicle.car'
  18: 'vehicle.construction'
  19: 'vehicle.emergency.ambulance'
  20: 'vehicle.emergency.police'
  21: 'vehicle.motorcycle'
  22: 'vehicle.trailer'
  23: 'vehicle.truck'
  24: 'flat.driveable_surface'
  25: 'flat.other'
  26: 'flat.sidewalk'
  27: 'flat.terrain'
  28: 'static.manmade'
  29: 'static.other'
  30: 'static.vegetation'
  31: 'vehicle.ego'
  32: 'empty'
labels_16:
  0: 'noise'
  1: 'barrier'
  2: 'bicycle'
  3: 'bus'
  4: 'car'
  5: 'construction_vehicle'
  6: 'motorcycle'
  7: 'pedestrian'
  8: 'traffic_cone'
  9: 'trailer'
  10: 'truck'
  11: 'driveable_surface'
  12: 'other_flat'
  13: 'sidewalk'
  14: 'terrain'
  15: 'manmade'
  16: 'vegetation'
  17: 'empty'
learning_map:
  1: 1
  5: 1
  7: 1
  8: 1
  10: 1
  11: 1
  13: 1
  19: 1
  20: 1
  0: 1
  29: 1
  31: 1
  9: 1
  14: 1
  15: 1
  16: 1
  17: 1
  18: 1
  21: 1
  2: 1
  3: 1
  4: 1
  6: 1
  12: 1
  22: 1
  23: 1
  24: 1
  25: 1
  26: 1
  27: 1
  28: 1
  30: 1
  32: 0